runtime: python27
api_version: 1
threadsafe: yes
instance_class: F4_HIGHMEM
handlers:
- url: /datastore.*
  script: datastore.app
- url: /memcache.*
  script: memcache.app
- url: /task.*
  script: taskqueue.app

automatic_scaling:
  target_cpu_utilization: 0.80
  min_instances: 20
  max_instances: 150
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 5